### ISSUE TITLE
Inconsistent output behaviour

### ISSUE THREAD

**Issue by NoctuaNivalis** [ianremmler/wjt#1]
I'm not sure if this was intentional or not, but it seems inconsistent to me. When called without any flags, wjt will output the selected value when (1) closing wjt by hitting enter and (2) when clicking somewhere on the selector.

I'd expect (2) only to happen when the `-t` flag is passed. After all, clicking somewhere on the bar is sort of scrolling.

(Thanks for creating this, btw, I didn't know what I was missing before.)

**Comment by ianremmler** [comment]
It was intentional, but I had a hard time deciding what the behavior should be.  I think what I want to do is to make outputting on keyboard change optional (probably default to on, as I find it more useful).  I will probably also add a "once" mode that will only print one value on exit, because I can see that being useful even though I haven't needed it for anything.  Hopefully that will cover the use cases.  I'm trying to keep the options from getting out of hand.

**Comment by ianremmler** [comment]
After thinking more about this, I am now leaning toward just always reporting (current track mode).  If you only want one value, just read in a loop until wjt exits and use the last value.  Keyboard and mouse input are different enough that it's hard to have an intuitive in between mode for both, and I can't think of a good use case for needing it, so simplicity wins.

**Comment by NoctuaNivalis** [comment]
Simplicity is the best. I was already using `wjt -t` in a sound volume adjusting script, and `wjt | tail -1` in another. Now I just have to leave out the `-t` and it'll all work.
