### ISSUE TITLE
Allow custom size and position

### ISSUE THREAD

**Issue by schaden-freude** [ianremmler/wjt#3]

**Comment by ikrabbe** [comment]
Choosing size and position is part of the window manager not of the application.
The application or the widgets can have geometric constraints, but in the end the window manager decides on size and more important, about position.

**Comment by ianremmler** [comment]
This is outside of the scope of the mainline features I think this simple tool should include, but it should hopefully be easy for a user to modify it to add this functionality.

**Comment by Arsaell** [comment]
[custom_geometry.txt](https://github.com/user-attachments/files/17693087/custom_geometry.txt)
I had the same interest as schaden-freude, so I went ahead and made the changes myself.

Here is a diff of a working solution, from commit "931b8f9dcf69c6aba152034560dcbde1aeeb6d18"

I didn't do thorough tests, notably because I don't have multiple monitors, but it works as intended on my machine.
